services:
  nginx:
    container_name: nginx
    build: frontend/nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./frontend:/var/www/html
  media:
    container_name: media
    build: media/nginx
    ports:
      - "9000:9000"
    volumes:
      - ./media/files:/data/files/
    restart: always
  user:
      container_name: user
      build: ./services/user
      volumes:
        - ./services/user:/app
      env_file:
        - .env
      restart: always
      networks:
        - services_network
  auth:
      container_name: auth
      build: ./services/auth
      volumes:
        - ./services/auth:/app
      env_file:
        - .env
      restart: always
      networks:
        - services_network
  gateway:
      container_name: gateway
      build: ./gateway
      ports:
        - "8000:8000"
      volumes:
        - ./gateway:/app
      env_file:
        - .env
      restart: always
      networks:
        - services_network
      depends_on:
        - user
        - auth

networks:
  services_network:
    driver: bridge