services:
  nginx:
    container_name: nginx
    build: frontend/nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./frontend:/var/www/html
  media:
    container_name: media
    build: media/nginx
    ports:
      - "9000:9000"
    volumes:
      - ./media/files:/data/files/
    restart: always
  user:
    container_name: user
    build: ./backend/user
    ports:
      - "4000:4000"
    volumes:
      - ./backend/user:/app
      - ./database:/database
    env_file:
      - .env
    restart: always
  auth:
    container_name: auth
    build: ./backend/auth
    ports:
      - "3000:3000"
    volumes:
      - ./backend/auth:/app
      - ./database:/database
    env_file:
      - .env
    restart: always
